### PR TITLE
Fix throwIfFalseEOF if skip method was called before read

### PR DESCRIPTION
**Pull request by medb**
throwIfFalseEOF method don't take into account bytes read/skipped in skip method and throws IOException when legit EOF was reached.

### CODE REVIEW

**Comment by chingor13** [comment]
Can we add a test for this?

It looks like we can add something like this:

```
  public void testSkippingBytes() throws IOException {
    MockHttpURLConnection connection = new MockHttpURLConnection(null)
        .setResponseCode(200)
        .setInputStream(new ByteArrayInputStream(StringUtils.getBytesUtf8("0123456789")))
        .addHeader("Content-Length", "10");
    NetHttpResponse response = new NetHttpResponse(connection);
    InputStream is = response.getContent();
    // read 1 byte, then skip 9 (to EOF)
    assertEquals('0', is.read());
    assertEquals(9, is.skip(9));
    // expect EOF, not an exception
    assertEquals(-1, is.read());
  }
```

**Comment by medb** [comment]
Thanks for the test, added it to PR

**Comment by chingor13** [comment]
@medb Is it possible to rebase these changes off of the "dev" branch? Strangely, the "dev" branch is the primary branch, not "master" and the CI config in that branch cannot be run.

**Comment by medb** [comment]
Rebased on `dev` branch

**Comment by chingor13** [comment]
Thanks!

**Pull request merged**
