### PR TITLE
Removed java.util.logging in favor of SLF4J as it is more universal

### PR DESCRIPTION
**Pull request by nterry**

### CODE REVIEW

**Comment by nterry** [comment]
I signed it!

**Comment by mattwhisenhunt** [comment]
Thank you for your pull request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.

**Comment by nterry** [comment]
@mattwhisenhunt Is there any movement on my request to reconsider this? Please see my justifications above.

Also, I don't see anywhere I can re-open this pull request.

**Comment by mattwhisenhunt** [comment]
I'll kick this over to @jadekler.

**Comment by jadekler** [comment]
cc @chingor13

**Comment by nterry** [comment]
@mattwhisenhunt @jadekler @chingor13  Can I get an update? It's been almost 2 months now...

**Comment by nterry** [comment]
@mattwhisenhunt @jadekler @chingor13 Any update?

**Pull request closed without merging**
