### PR TITLE
Add HTTP PATCH support

### PR DESCRIPTION
**Pull request by nonexpectation**

### CODE REVIEW

**Comment by nonexpectation** [comment]
I signed it!

**Comment by nonexpectation** [comment]
I signed it!

**Comment by ejona86** [comment]
I'm researching whether PATCH is actually supported on appengine.

**Comment by nonexpectation** [comment]
I was able to send a request with something like this on appengine with no issues:
```java
	    URLFetchService urlFetchService = URLFetchServiceFactory.getURLFetchService();
	    com.google.appengine.api.urlfetch.HTTPRequest request = new com.google.appengine.api.urlfetch.HTTPRequest(new URL("url"), HTTPMethod.PATCH);
...more setup...
	    urlFetchService.fetch(request);
```

I'm not sure if that's officially supported or not.

**Comment by ejona86** [comment]
Yeah, I'm investigating for official support.

**Comment by ejona86** [comment]
I'm not having enough time to investigate. It is publicly documented for Python and works for you in App Engine. That's enough for me at this point.

Cherry-picked as 7f68cf47

**Comment by ejona86** [comment]
Oh, and thank you!

**Pull request closed without merging**
