### PR TITLE
Support Arrays.asList in GenericData cloning

### LINKED ISSUE #293: GenericJson.clone() method blows up when trying to clone Google reads
From the Hellbender project (broadinstitute/hellbender#650):

When we copy a Google read (ie., a com.google.api.services.genomics.model.Read), we currently call into the GenericJson.clone() method, which uses reflection to deep copy the fields. However, this method seems to incorrectly try to instantiate a java.util.Arrays$ArrayList instead of a java.util.ArrayList, causing it to blow up during BQSR runs (as reported by @jean-philippe-martin):

    [Jul-13 1:36 PM] JP Martin: 
    2015-07-13T17:36:00.151Z: Error:  (5361981f0726257c): java.lang.IllegalArgumentException: unable to create new instance of class java.util.Arrays$ArrayList possibly because it is not public
    at com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:165)
    at com.google.api.client.util.Types.newInstance(Types.java:120)
    at com.google.api.client.util.Data.clone(Data.java:220)
    at com.google.api.client.util.Data.deepCopy(Data.java:307)
    at com.google.api.client.util.Data.clone(Data.java:222)
    at com.google.api.client.util.Data.deepCopy(Data.java:293)
    at com.google.api.client.util.GenericData.clone(GenericData.java:172)
    at com.google.api.client.json.GenericJson.clone(GenericJson.java:90)
    at com.google.api.services.genomics.model.Read.clone(Read.java:548)
    at org.broadinstitute.hellbender.utils.read.GoogleGenomicsReadToGATKReadAdapter.copy(GoogleGenomicsReadToGATKReadAdapter.java:619)

### PR DESCRIPTION
**Pull request by ejona86**
Resolves #293

@davidadamsphd, are you able to give this a try?

### CODE REVIEW

**Comment by davidadamsphd** [comment]
I hadn't yet. I hope to be able to do it today.

**Comment by jean-philippe-martin** [comment]
@ejona86, thanks for writing this! I was able to give it a try and it works for me.

**Comment by ejona86** [comment]
@jean-philippe-martin, excellent. Thanks!

@davidadamsphd, could you review this code and give LGTM if it seems good?

**Comment by davidadamsphd** [comment]
LGTM!
Now, when can we expect to see a new release on Maven :)

**Comment by ejona86** [comment]
It's going to be a bit until a release happens, but I have made new snapshots in Sonatype's repository: https://oss.sonatype.org/content/repositories/snapshots/

To use the snapshots with Gradle, depend on 1.21.0-SNAPSHOT and add to your build.gradle:
```gradle
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}
```

**Pull request merged**
