### PR TITLE
Add j2objc reflection for json and util package

### PR DESCRIPTION
**Pull request by xiaojiej**

### CODE REVIEW

**Comment by jadekler** [comment]
Note to future releaser: BUILD files will need to be modified as part of this import.

**Comment by jadekler** [comment]
Also, this is failing in CI:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project google-http-client: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/google/google-http-java-client/google-http-client/src/main/java/com/google/api/client/json/package-info.java:[27,36] error: package com.google.j2objc.annotations does not exist
[ERROR] /home/travis/build/google/google-http-java-client/google-http-client/src/main/java/com/google/api/client/util/package-info.java:[25,36] error: package com.google.j2objc.annotations does not exist
[ERROR] /home/travis/build/google/google-http-java-client/google-http-client/src/main/java/com/google/api/client/json/package-info.java:[24,1] error: cannot find symbol
[ERROR]  class ReflectionSupport
[ERROR] /home/travis/build/google/google-http-java-client/google-http-client/src/main/java/com/google/api/client/util/package-info.java:[22,1] error: cannot find symbol
```

**Comment by chingor13** [comment]
It looks like the google-http-client artifact's pom.xml also needs the dependency added.

**Comment by xiaojiej** [comment]
PTAL, updated the dependency in pom files

**Comment by xiaojiej** [comment]
Libraries that uses google-http-java-client with J2ObjC enabled can pass in a --strip-reflection flag to improve build and startup performance for iOS apps

**Pull request merged**
